import { StyleSheet } from "react-native";
import { windowWidth, windowHeight } from "../components/Dimention";
export const Styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  body: {
    paddingHorizontal: 20,
  },
  scrollView: {
    marginTop: 10,
    marginBottom: 10,
  },
  img: {
    width: windowWidth - 50,
    height: windowHeight / 4,
    borderRadius: 10,
    marginBottom: 10,
  },
  textHeader_H: {
    color: "#000",
    fontSize: 18,
    marginBottom: 10,
  },
  title: {
    color: "#026487",
    fontSize: 18,
    padding: 10,
    marginHorizontal: 10,
    borderBottomWidth: 1,
    borderColor: "#026487",
  },
  box: {
    backgroundColor: "#fff",
    borderRadius: 10,
    marginTop: 5,
  },
  icon: {
    padding: 10,
  },
  text_detail: {
    color: "#000",
    fontSize: 16,
    marginBottom: 10,
  },
  featured_inner: {
    backgroundColor: "#fff",
    borderRadius: 10,
    marginTop: 5,
    marginBottom: 5,
    paddingVertical: 20,
  },
  featured_title: {
    fontSize: 16,
    color: "#000",
    alignItems: "center",
  },
  featured_detail: {
    fontSize: 14,
    color: "#000",
    marginLeft: 15,
    marginRight: 10,
  },
  box_bnt: {
    padding: 5,
  },
  btn: {
    width: 150,
    height: 50,
    borderRadius: 10,
    backgroundColor: "#026487",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  btn_text: {
    fontSize: 16,
    color: "#fff",
    padding: 10,
  },
  btn_r: {
    width: 150,
    height: 50,
    borderWidth: 0.5,
    borderColor: "#026487",
    borderRadius: 10,
    backgroundColor: "#fff",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  btn_text_r: {
    fontSize: 16,
    color: "#026487",
    padding: 10,
  },
  btn_row: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 10,
  },
  featured_box_title: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginHorizontal: 15,
  },
  protec_text: {
    fontSize: 16,
    padding: 10,
    marginHorizontal: 15,
    color: "#000",
  },
  More_details_text: {
    color: "red",
    fontSize: 16,
  },
  Other: {
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  OtherBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderRadius: 10,
    marginHorizontal: 15,
    borderWidth: 1,
    borderColor: "#026487",
    paddingHorizontal: 10,
  },
  OtherBox_r: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#026487",
    borderRadius: 10,
    marginHorizontal: 15,
    borderWidth: 1,
    borderColor: "#fff",
    paddingHorizontal: 10,
  },

  More_details_box: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderRadius: 10,
    marginHorizontal: 15,
    borderWidth: 1,
    borderColor: "red",
    paddingHorizontal: 10,
  },
  OtherText: {
    color: "#026487",
    fontSize: 16,
  },
  OtherText_r: {
    color: "#fff",
    fontSize: 16,
  },
  contact: {
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  contactBox_L: {
    width: 140,
    height: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#026487",
    borderRadius: 10,
    marginHorizontal: 15,
    borderWidth: 1,
    borderColor: "#fff",
    paddingHorizontal: 10,
  },
  contactBox_R: {
    width: 150,
    height: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderRadius: 10,
    marginHorizontal: 15,
    borderWidth: 1,
    borderColor: "#026487",
    paddingHorizontal: 10,
  },
  text_title_blue: {
    fontSize: 18,
    color: "#026487",
    paddingTop: 10,
    paddingBottom: 10,
  },
  text_title_blue_bt: {
    fontSize: 18,
    color: "#026487",
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 20,
  },
});
